### ISSUE TITLE
Android 12 permissions crashes app

### ISSUE THREAD

**Issue by GiulioWecove** [awazgyawali/flutter_stripe_terminal#13]
When I run my app on Android 12 devices, whenever I let the user ask for permission(every permission) it crashes and give's me this error:

`E/AndroidRuntime(13170): 	at com.stripe.stripeterminal.PermissionsValidator.validatePermissionsPre31(PermissionsValidator.kt:34)
E/AndroidRuntime(13170): 	at com.stripe.stripeterminal.PermissionsValidator.validatePermissions$core_publish(PermissionsValidator.kt:14)
E/AndroidRuntime(13170): 	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:839)
E/AndroidRuntime(13170): 	at com.stripe.stripe_terminal.StripeTerminalPlugin._startStripe(StripeTerminalPlugin.kt:78)
E/AndroidRuntime(13170): 	at com.stripe.stripe_terminal.StripeTerminalPlugin.onRequestPermissionsResult(StripeTerminalPlugin.kt:568)
E/AndroidRuntime(13170): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(13170): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(13170): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:757)
E/AndroidRuntime(13170): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(13170): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8532)
E/AndroidRuntime(13170): 	at android.app.Activity.dispatchActivityResult(Activity.java:8389)
E/AndroidRuntime(13170): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
E/AndroidRuntime(13170): 	... 13 more
I/Process (13170): Sending signal. PID: 13170 SIG: 9
Lost connection to device.
`
If you can investigate it will be very helpful, thank you.

My flutter environment: 

`[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability`

**Comment by GiulioWecove** [comment]
To be more specific.. 

If I grant BT permissions the app crasher telling me that stripe terminal needs Location: 

`E/AndroidRuntime(12571): 	at android.app.ActivityThread.main(ActivityThread.java:7941)
E/AndroidRuntime(12571): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12571): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(12571): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
E/AndroidRuntime(12571): Caused by: com.stripe.stripeterminal.external.models.TerminalException: You must request location permissions before initializing the Terminal
E/AndroidRuntime(12571): 	at com.stripe.stripeterminal.PermissionsValidator.validatePermissionsPre31(PermissionsValidator.kt:34)
E/AndroidRuntime(12571): 	at com.stripe.stripeterminal.PermissionsValidator.validatePermissions$core_publish(PermissionsValidator.kt:14)
E/AndroidRuntime(12571): 	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:839)
E/AndroidRuntime(12571): 	at com.stripe.stripe_terminal.StripeTerminalPlugin._startStripe(StripeTerminalPlugin.kt:78)
E/AndroidRuntime(12571): 	at com.stripe.stripe_terminal.StripeTerminalPlugin.onRequestPermissionsResult(StripeTerminalPlugin.kt:568)
E/AndroidRuntime(12571): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:777)
E/AndroidRuntime(12571): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:409)
E/AndroidRuntime(12571): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:757)
E/AndroidRuntime(12571): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:748)
E/AndroidRuntime(12571): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8537)
E/AndroidRuntime(12571): 	at android.app.Activity.dispatchActivityResult(Activity.java:8394)
E/AndroidRuntime(12571): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5357)
E/AndroidRuntime(12571): 	... 13 more`

Viceversa if I first grant permissions to Location before the location it crasher telling me that he needs BT permission.

If i grant all permissions and initialize the Stripe plugin, it crasher with this message:
`E/flutter (13577): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(stripeTerminal#insuffecientPermission, You have not provided enough permission for the scanner to work, null, null)
E/flutter (13577): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter (13577): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter (13577): <asynchronous suspension>
E/flutter (13577): #2      StripeTerminal.getInstance
package:stripe_terminal/stripe_terminal.dart:58
E/flutter (13577): <asynchronous suspension>
E/flutter (13577): #3      TerminalStateController.initStripe
package:wecove_connnect/controllers/terminal_state_controller.dart:47
E/flutter (13577): <asynchronous suspension>
E/flutter (13577):`

I've already check and there's all permissions for Bluetooth and location.

**Comment by yazanturk** [comment]
any soluation ?

**Comment by GiulioWecove** [comment]
> any soluation ?

I haven't found any solution and the author of the package is not replying, I'm just hoping that flutter stripe (official package) release their terminal connection part.

**Comment by kekko7072** [comment]
@GiulioWecove  @yazanturk  I've seen there is one new package based on this one: [NEW PACKAGES BASED ON THIS ONE](https://pub.dev/packages/flutterflow_stripe_terminal)

**Comment by GiulioWecove** [comment]
@kekko7072 have you tried it?

**Comment by kekko7072** [comment]
> @kekko7072 have you tried it?

@GiulioWecove finally I used another package mek_stripe_terminal: ^1.0.0
